<?php


/**
 * @param $data
 * @param $route_name
 */
function wm_webform_simplifier_menu_local_tasks_alter(&$data, $route_name)
{

    // Disable a bunch of local tasks to ensure the survival of the human race.
    $account = \Drupal::currentUser()->hasPermission('use advanced webform configuration');
    if (!$account) {
        if (isset($data['tabs'][0]['webform.settings'])) {
            $data['tabs'][0]['webform.settings']['#access'] = false;
        }
        if (isset($data['tabs'][0]['webform.addons'])) {
            $data['tabs'][0]['webform.addons']['#access'] = false;
        }
        if (isset($data['tabs'][1]['entity.webform.edit_form_settings'])) {
            $data['tabs'][1]['entity.webform.edit_form_settings']['#access'] = false;
        }
        if (isset($data['tabs'][1]['entity.webform.edit_form_access'])) {
            $data['tabs'][1]['entity.webform.edit_form_access']['#access'] = false;
        }
        if (isset($data['tabs'][1]['entity.webform.edit_form_assets'])) {
            $data['tabs'][1]['entity.webform.edit_form_assets']['#access'] = false;
        }
        if (isset($data['tabs'][1]['entity.webform.edit_form_handlers'])) {
            $data['tabs'][1]['entity.webform.edit_form_handlers']['#access'] = false;
        }
        //'entity.webform.edit_form_third_party_settings'
        if (isset($data['tabs'][1]['entity.webform.edit_form_third_party_settings'])) {
            $data['tabs'][1]['entity.webform.edit_form_third_party_settings']['#access'] = false;
        }
    }
}

/**
 * @param $form
 * @param $form_state
 */
function wm_webform_simplifier_form_webform_form_alter(&$form, &$form_state)
{
    // Don't show the category stuff.
    $account = \Drupal::currentUser()->hasPermission('use advanced webform configuration');
    if (!$account) {
        $form['category']['#access'] = false;
    }
}

/**
 * Remove certain parts to ensure a client or less advanced user messes up the site.
 * @param $form
 * @param $form_state
 */
function wm_webform_simplifier_form_webform_settings_form_alter(&$form, &$form_state)
{
    $account = \Drupal::currentUser()->hasPermission('use advanced webform configuration');
    if (!$account) {
        $form['attributes']['#access'] = false;
        $form['page']['#access'] = false;
        $form['form']['form_submit']['form_submit_attributes']['#access'] = false;
        $form['preview']['settings']['preview_next_button']['preview_next_button_attributes']['#access'] = false;
        $form['preview']['settings']['preview_prev_button']['preview_prev_button_attributes']['#access'] = false;
        $form['wizard']['wizard_next_button']['wizard_next_button_attributes']['#access'] = false;
        $form['wizard']['wizard_prev_button']['wizard_prev_button_attributes']['#access'] = false;
    }

}

/**
 * Remove certain parts to ensure a client or less advanced user messes up the site.
 * @param $form
 * @param $form_state
 */
function wm_webform_simplifier_form_webform_access_form_alter(&$form, &$form_state)
{
    $account = \Drupal::currentUser()->hasPermission('use advanced webform configuration');
    if (!$account) {
        $form['access']['#access'] = false;
        $form['actions']['submit']['#access'] = false;
    }
}

/**
 * Remove certain parts to ensure a client or less advanced user messes up the site.
 * @param $form
 * @param $form_state
 */
function wm_webform_simplifier_form_webform_ui_element_form_alter(&$form, &$form_state)
{
    dpm(array_keys($form['properties']));
    $account = \Drupal::currentUser()->hasPermission('use advanced webform configuration');
    if (!$account) {
        $form['properties']['access']['#access'] = false;
        $form['properties']['element_attributes']['#access'] = false;
        $form['properties']['wrapper_attributes']['#access'] = false;
        $form['properties']['validation']['#access'] = false;
        $form['properties']['conditional']['#access'] = false;
        $form['properties']['display']['#access'] = false;
        $form['properties']['admin']['#access'] = false;
        $form['properties']['access_create']['#access'] = false;
        $form['properties']['access_update']['#access'] = false;
        $form['properties']['access_view']['#access'] = false;
        $form['properties']['form']['#access'] = false;
    }

}
